name: Build AridityTeam.Ascorbic

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        dotnet: [ "8.0", "10.0" ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Install Git on Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update && sudo apt-get install -y git

    - name: Install Git on macOS
      if: runner.os == 'macOS'
      run: |
        brew install git

    - name: Install Windows .NET Framework targeting pack
      if: runner.os == 'Windows'
      run: choco install netfx-4.7.2-devpack -y

    - name: Restore dependencies
      run: dotnet restore

    - name: Build library
      run: dotnet build --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test --framework net10.0 --configuration Release --no-build
