name: Build AridityTeam.Ascorbic
permissions:
  contents: write
on:
  push:
    branches: [ "master" ]
    paths:
        - ".github/workflows/**"
        - "src/**"
        - "Directory.Build.props"
        - "Directory.Packages.props"
  pull_request:
    branches: [ "master" ]
    paths:
        - ".github/workflows/**"
        - "src/**"
        - "Directory.Build.props"
        - "Directory.Packages.props"

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        dotnet: [ "8.0", "10.0" ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Install Windows .NET Framework targeting pack
      if: runner.os == 'Windows'
      run: choco install netfx-4.7.2-devpack -y

    - name: Restore dependencies
      run: dotnet restore

    - name: Build library
      run: dotnet build --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test --framework net10.0 --configuration Release --no-build --filter FullyQualifiedName!~AridityTeam.Ascorbic.Tests.Util.Git
