name: Publish NuGet Package

permissions:
  contents: write
  packages: write

on:
  release:
    types: [published, prereleased]
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release event to simulate (e.g., published)'
        required: true
        default: 'published'

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: |
          if [ "${{ github.event.release.prerelease }}" = "true" ]; then
            echo "Building Debug for pre-release"
            dotnet build --no-restore -c Debug
          else
            echo "Building Release for full release"
            dotnet build --no-restore -c Release
          fi

      - name: Pack the NuGet package
        run: |
          if [ "${{ github.event.release.prerelease }}" = "true" ]; then
            dotnet pack --no-build -c Debug -o nupkgs /p:Version=${{ github.event.release.tag_name }}
          else
            dotnet pack --no-build -c Release -o nupkgs /p:Version=${{ github.event.release.tag_name }}
          fi

      - name: Publish to NuGet.org
        run: dotnet nuget push "nupkgs/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

      - name: Push to GitHub Packages
        run: |
          dotnet nuget push ./dist/*.nupkg \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
